name: First YAML file

on:
  push:
    branches:
      - "main"

jobs:
  first-job:
    name: First job
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Print working directory
        run: pwd
